#! /bin/sh

sxhkd &

bspc config border_width         1
bspc config window_gap           3

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config top_padding    38
bspc config bottom_padding 102


bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Docky layer=above border=off manage=on

xrdb ~/.Xresources &
feh --bg-scale ~/Pictures/Wallpaper/wallpaper.jpg &
yabar &
docky &
compton
