#! /bin/sh

sxhkd &

bspc config border_width         1
bspc config window_gap          17

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config top_padding 40
bspc config bottom_padding 100


bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrdb ~/.Xresources &
feh --bg-scale ~/Pictures/Wallpaper/wallpaper.jpg &
yabar &
docky &
compiz ccp
