#! /bin/sh

sxhkd &

bspc config border_width         1
bspc config window_gap           45

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config focused_border_color "#A020F0"

bspc config initial_polarity second_child

bspc config top_padding    45
bspc config bottom_padding 45

bspc monitor -d I II III IV V VI VII VIII IX X


xrdb ~/.Xresources &
yabar &
lemonbuddy_wrapper bottom &
compton --config ~/dotfiles/compton.conf & 
feh --bg-scale ~/Pictures/Wallpaper/space.jpg
